openapi: 3.0.0
info:
  title: Tshirt store API
  description: LCO - course to create API for ecom store
  version: 1.1.0
  contact:
    email: madan@go.co
    url: "https://mad.dev"

# servers:
#   - url: "https://localhost:4000/api/v1"
#     description: localhost - secure
#   - url: "http://localhost:4000/api/v1"
#     description: localhost - regular

servers:
  - url: "{protocols}://localhost:4000/api/{versions}"
    description: localhost
    variables:
      versions:
        enum:
          - v1
          - v2
        default: v1
      protocols:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    cookiesAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /dummy:
    get:
      tags:
        - Home
      summary: returns a greet message
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad request
        500:
          description: internal server error